helloworld_project/event_api/urls.py
from django.urls import path

from .views import (
    EventAPI,
    EventAttendeeAPI,
    EventDetailAPI,
    EventSongsView,
    EventView,
    SongAtEventMappingAPI,
    SongAtEventMappingDetailAPI,
)

urlpatterns = [
    path("events/", EventAPI.as_view(), name="events"),
    path("events/<int:pk>/", EventDetailAPI.as_view(), name="events_detail"),
    path("mappings/", SongAtEventMappingAPI.as_view(), name="mappings"),
    path(
        "mappings/<int:pk>/",
        SongAtEventMappingDetailAPI.as_view(),
        name="mappings_detail",
    ),
    path("event_attendees/", EventAttendeeAPI.as_view(), name="event_attendees"),
    path("event/<int:event_id>/songs/", EventSongsView.as_view(), name="event_songs"),
    path("event/list/", EventView.as_view(), name="event_list"),
]

helloworld_project/hello/urls.py
from django.urls import path

from . import views

# creating URLconf
urlpatterns = [
    path("", views.hello_world, name="hello_world"),
]

helloworld_project/helloworld_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path(
        "accounts/",
        include(("user_management.urls", "user-management"), namespace="user"),
    ),
    path("admin/", admin.site.urls),
    path("", include(("hello.urls", "hello"), namespace="home")),
    path("song-api/", include(("song_api.urls", "song-api"), namespace="song-api")),
    path("event-api/", include(("event_api.urls", "event-api"), namespace="event-api")),
]

helloworld_project/event_api/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from song_api.models import Song, SongCatalog


class Event(models.Model):
    event_name = models.CharField(max_length=250, unique=True)
    event_date = models.DateField()
    create_date = models.DateField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)
    song_catalog = models.ForeignKey(SongCatalog, on_delete=models.CASCADE)
    event_organizer = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )

    def __str__(self) -> str:
        return f"{self.event_name} at {self.event_date}"


class SongAtEventMapping(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    mapper = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        indexes = [
            models.Index(fields=["mapper"]),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=["event", "song"], name="unique_song_per_event"
            )
        ]

    def save(self, *args, **kwargs):
        if not self.event.event_organizer == self.mapper:
            if not EventAttendee.objects.filter(
                event=self.event, attendee=self.mapper
            ).exists():
                raise ValidationError(
                    f"The mapper is not an attendee of this event or {self.event.event_organizer} is not {self.mapper}."
                )
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.song.song_title} ({self.song.artist}) played at {self.event.event_name} event"


class EventAttendee(models.Model):
    event = models.ForeignKey("Event", on_delete=models.CASCADE)
    attendee = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="attended_events"
    )
    create_date = models.DateField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)

    class Meta:
        unique_together = (
            "event",
            "attendee",
        )

    def __str__(self) -> str:
        return f"{self.attendee} is attending {self.event.event_name} on {self.event.event_date}"

helloworld_project/event_api/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.postgres.search import SearchQuery, SearchRank
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
from rest_framework import generics, status
from rest_framework.permissions import AllowAny, IsAdminUser, IsAuthenticated
from rest_framework.response import Response
from song_api.models import Song

from .models import Event, EventAttendee, SongAtEventMapping
from .serializers import (
    EventAttendeeSerializer,
    EventSerializer,
    SongAtEventMappingSerializer,
)


class EventPermissionMixin(UserPassesTestMixin):
    def test_func(self):
        user = self.request.user
        event_id = self.kwargs.get("event_id")
        event = get_object_or_404(Event, id=event_id)

        if user.is_superuser:
            return True
        if event.event_organizer == user:
            return True
        if EventAttendee.objects.filter(event=event, attendee=user.id).exists():
            return True

        return False


class EventAPI(generics.ListCreateAPIView):
    serializer_class = EventSerializer
    permission_classes = [IsAuthenticated]

    def get_permissions(self):
        """
        Override to customize permission for different actions.
        """
        if self.request.method == "GET":
            return [AllowAny()]
        return [IsAdminUser()]

    def get_queryset(self):
        queryset = Event.objects.all()
        organizer = self.request.query_params.get("organizer")
        event_name = self.request.query_params.get("event_name")
        date = self.request.query_params.get("date")

        if organizer is not None:
            queryset = queryset.filter(event_organizer=organizer)
        if event_name is not None:
            queryset = queryset.filter(event_name__icontains=event_name)
        if date is not None:
            queryset = queryset.filter(date=date)

        return queryset


class EventDetailAPI(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = EventSerializer
    queryset = Event.objects.all()
    permission_classes = [IsAuthenticated]


class SongAtEventMappingAPI(generics.ListCreateAPIView):
    serializer_class = SongAtEventMappingSerializer

    def get_permissions(self):
        """
        Override to customize permission for different actions.
        """
        if self.request.method == "GET":
            return [AllowAny()]
        return [IsAuthenticated()]

    def get_queryset(self):
        queryset = SongAtEventMapping.objects.all()
        event = self.request.query_params.get("event")
        if event is not None:
            queryset = queryset.filter(event=event)
        return queryset

    def create(self, request, *args, **kwargs):
        event_id = request.data.get("event")
        mapper_id = request.data.get("mapper")
        songs = request.data.get("songs")

        if not event_id or not mapper_id or not songs:
            return Response(
                {"detail": "Invalid request"}, status=status.HTTP_400_BAD_REQUEST
            )

        event = get_object_or_404(Event, id=event_id)
        mapper = get_object_or_404(User, id=mapper_id)

        for song_id in songs:
            song = get_object_or_404(Song, id=song_id)
            SongAtEventMapping.objects.create(event=event, mapper=mapper, song=song)

        return Response(
            {"detail": "Mappings created successfully"}, status=status.HTTP_201_CREATED
        )


class SongAtEventMappingDetailAPI(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = SongAtEventMappingSerializer
    queryset = SongAtEventMapping.objects.all()
    permission_classes = [IsAuthenticated]


class EventAttendeeAPI(EventPermissionMixin, generics.ListCreateAPIView):
    serializer_class = EventAttendeeSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = EventAttendee.objects.filter(
            event__event_organizer=self.request.user
        )
        return queryset

    def perform_create(self, serializer):
        if self.request.user != serializer.validated_data["event"].event_organizer:
            raise PermissionDenied("You are not the organizer of this event.")
        serializer.save()


class EventSongsView(LoginRequiredMixin, ListView):
    model = Song
    template_name = "event_api/song_mapper.html"
    context_object_name = "songs"

    def get_queryset(self, song_catalog_id):
        query = self.request.GET.get("q", "")
        if query:
            search_query = SearchQuery(query)
            return (
                Song.objects.annotate(rank=SearchRank("search_vector", search_query))
                .filter(search_vector=search_query, song_catalog=song_catalog_id)
                .order_by("-rank")
            )
        else:
            return Song.objects.filter(song_catalog=song_catalog_id)

    def get(self, request, *args, **kwargs):
        event_id = kwargs.get("event_id")
        event = get_object_or_404(Event, id=event_id)

        songs = self.get_queryset(event.song_catalog)

        song_mappings = SongAtEventMapping.objects.filter(event=event)
        song_mapper_dict = {
            mapping.song_id: (mapping.mapper_id, mapping.id)
            for mapping in song_mappings
        }

        for song in songs:
            if song.id in song_mapper_dict:
                song.is_selected = True
                if song_mapper_dict[song.id][0] == request.user.id:
                    song.can_delete = True
                    song.mapping_id = song_mapper_dict[song.id][1]
            else:
                song.is_selected = False
                song.can_delete = False

        return render(request, self.template_name, {"event": event, "songs": songs})


class EventView(LoginRequiredMixin, ListView):
    model = Event
    template_name = "event_api/events.html"
    context_object_name = "events"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

    def get(self, request, *args, **kwargs):
        events = self.get_queryset()
        for event in events:
            if event.event_organizer == request.user:
                event.can_delete = True

        return render(
            request, self.template_name, {"events": events, "user": request.user}
        )

helloworld_project/event_api/templates/event_api/events.html
{% extends "base.html" %}

{% block content %}
    <h1>Pick an event, {{ user }} !</h1>
    {% for event in events %}
    <li>
        <a href="{% url 'event-api:event_songs' event_id=event.id %}">{{ event.event_name }} on {{ event.event_date }} {% if event.can_delete %} (Deletable) {% endif %} </a>
    </li>
    {% endfor %}
{% endblock %}
```

helloworld_project/event_api/templates/event_api/song_mapper.html
{% extends "base.html" %}

{% block title %}
    Pick the songs you want to play at {{ event.event_name }}
{% endblock %}

{% block content %}
    <h1>Pick the songs you want to play at {{ event.event_name }}</h1>
    <form id="songForm" method="post">
        {% csrf_token %}
        <input type="hidden" name="event" value="{{ event.id }}">
        <input type="hidden" name="mapper" value="{{ request.user.id }}">
        {% for song in songs %}
            <li>
                <input type="checkbox" name="song" value="{{ song.id }}">
                {{ song.song_title }} by {{ song.artist }} {% if song.is_selected %}(Selected){% endif %}
                {% if song.can_delete %}
                    <button type="button" onclick="deleteSong('{% url 'event-api:mappings_detail' song.mapping_id %}')">Delete {{ song.mapping_id }}</button>
                {% endif %}
            </li>
        {% endfor %}
        <input type="submit" value="Add songs">
    </form id="songForm">

    <script>
        function deleteSong(deleteUrl) {

            fetch(deleteUrl, {
                method: "DELETE",
                headers: {
                    "X-CSRFToken": "{{ csrf_token }}"
                }
            })
            .then(function(response) {
                if (response.ok) {
                    // Reload the current page
                    location.reload();
                } else {
                    console.error("Error:", response.statusText);
                }
            })
            .catch(function(error) {
                console.error("Error:", error);
            });
        }

        document.getElementById("songForm").addEventListener("submit", function(event) {
            event.preventDefault();

            // Get the selected songs
            var selectedSongs = Array.from(document.querySelectorAll('input[name="song"]:checked')).map(function(song) {
                return song.value;
            });

            // Create the JSON payload
            var payload = {
                "event": {{ event.id }},
                "songs": selectedSongs,
                "mapper": {{ request.user.id }}
            };

            // Send the POST request
            fetch("{% url 'event-api:mappings' %}", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "X-CSRFToken": "{{ csrf_token }}"
                },
                body: JSON.stringify(payload)
            })
            .then(function(response) {
                if (response.ok) {
                    // Reload the current page
                    location.reload();
                } else {
                    console.error("Error:", response.statusText);
                }
            })
            .catch(function(error) {
                console.error("Error:", error);
            });
        });
    </script>


{% endblock %}