helloworld_project/event_api/urls.py
from django.urls import path

from .views import (
    EventAPI,
    EventAttendeeAPI,
    EventDetailAPI,
    EventSongsView,
    EventView,
    SongAtEventMappingAPI,
    SongAtEventMappingDetailAPI,
)

urlpatterns = [
    path("events/", EventAPI.as_view(), name="events"),
    path("events/<int:pk>/", EventDetailAPI.as_view(), name="events_detail"),
    path("mappings/", SongAtEventMappingAPI.as_view(), name="mappings"),
    path(
        "mappings/<int:pk>/",
        SongAtEventMappingDetailAPI.as_view(),
        name="mappings_detail",
    ),
    path("event_attendees/", EventAttendeeAPI.as_view(), name="event_attendees"),
    path("event/<int:event_id>/songs/", EventSongsView.as_view(), name="event_songs"),
    path("event/list/", EventView.as_view(), name="event_list"),
]

helloworld_project/hello/urls.py
from django.urls import path

from . import views

# creating URLconf
urlpatterns = [
    path("", views.hello_world, name="hello_world"),
]

helloworld_project/helloworld_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path(
        "accounts/",
        include(("user_management.urls", "user-management"), namespace="user"),
    ),
    path("admin/", admin.site.urls),
    path("", include(("hello.urls", "hello"), namespace="home")),
    path("song-api/", include(("song_api.urls", "song-api"), namespace="song-api")),
    path("event-api/", include(("event_api.urls", "event-api"), namespace="event-api")),
]

helloworld_project/song_api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("songs/", views.SongList.as_view(), name="song-list"),
    path("songs/<int:pk>/", views.SongUpdateDelete.as_view(), name="song-detail"),
    path("search/", views.SongSearchList.as_view(), name="song-search"),
    path("v-song-search/", views.SongSearchList.as_view(), name="v-song-search"),
    path("catalogs/", views.SongCatalogList.as_view(), name="song-catalog-list"),
    path(
        "catalogs/<int:pk>/",
        views.SongCatalogUpdateDelete.as_view(),
        name="song-catalog-detail",
    ),
]

helloworld_project/user_management/urls.py
from django.urls import include, path

from .views import SignUpView, profile

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("profile/", profile, name="profile"),
]

helloworld_project/templates/includes/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:hello_world' %}">My App</a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            Hi {{ user.username }}!
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:signup' %}">Sign up</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'event-api:event_list' %}">Events</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'song-api:v-song-search' %}">Songs</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>